### ISSUE TITLE
Searching by type of main scheme results in garbled UI. 

### ISSUE THREAD

**Issue by ScottWoodward** [zzorba/marvelsdb#10]
Search criteria: 

- **t:main_scheme** (after posting is converted to **t:"main_scheme"**) 
- **Sort by Name**
- **View as Spoiler** OR **View as Full Cards**
- **All Cards**
- **Show Encounter Spoilers**

![image](https://user-images.githubusercontent.com/2498171/70203695-bfd8bf00-16eb-11ea-9ec4-ab6c34713864.png)

Example URL to reproduce: https://marvelcdb.com/find?q=t%3Amain_scheme&sort=name&view=card&decks=all

Issue occurs in Chrome, Firefox, and Edge.

**Comment by Kamalisk** [comment]
should be fixed now. refresh if it still looks broken.
