### ISSUE TITLE
Certain Villain and Main Scheme cards incorrectly have a boost value. 

### ISSUE THREAD

**Issue by ScottWoodward** [zzorba/marvelsdb#11]
For example, Ultron 1, 2, 3; The Crimson Cowl; Countdown to Oblivion; Assault on NORAD

Assault on Norad also lists a boost effect that does not exist. 

![image](https://user-images.githubusercontent.com/2498171/70203837-4f7e6d80-16ec-11ea-84f4-a84b32fae338.png)

**Comment by zzorba** [comment]
Thanks for the report, we initially had the numbers wrong on these cards (when I read some very fuzzy pictures incorrectly), so they inadvertently got stored in the DB incorrectly and the later corrections have messed things up.

@Kamalisk what's the best way to go about fixing this, should we make the importer null out boost for cards of this type (villain/main_scheme)?

**Comment by Kamalisk** [comment]
I can null all boost icons and reimport everything to reset all the values.

**Comment by Kamalisk** [comment]
which I did, and reimported. Should be fixed now.
