### ISSUE TITLE
Username faction colors not working for Encounter, Hero, Campaign

### ISSUE THREAD

**Issue by Scholeologist** [zzorba/marvelsdb#112]
The account settings include setting a faction color (setting links to the username to include, for example, `class = username fg-aggression` ) set appropriate colors for Protection, Leadership, Justice, Aggression, and Basic, but not for Encounter, Hero, or Campaign.  For these, the color is the same as if no faction color had been set in the user profile: `class username fg-campaign` has the same effect as `class username fg-`

**Comment by Kamalisk** [comment]
those do not have colors for them other than just the regular font color. They are just in the list as a side effect of being factions internally. When i revisit the profile page, I can take a look but otherwise will just be a weird side effect.
