### ISSUE TITLE
Data Issue - Hulk 

### ISSUE THREAD

**Issue by R3liant** [zzorba/marvelsdb#115]
All of Hulk's signature cards have two very different card numbers listed.  For instance, Immovable Object 10010 which is a one of card is listed as Hulk card #10 and #15.  The card is actually 15/15.

Please review and correct all of Hulk's cards.

Thank you.

**Comment by Kamalisk** [comment]
there are two different numbers for hero cards, the position in the pack itself, which in this case is 10 for Immovable Object, and then there is the position of the card in the hulk set, which is 15 (this takes into account the multiple copies of certain hero cards)
