### ISSUE TITLE
API access

### ISSUE THREAD

**Issue by twistedsistem** [zzorba/marvelsdb#12]
I am developing an OCTGN plugin for Marvel Champions and have it linking to the public api to allow users to build a deck quickly. I have requests from users to be able to pull their saved decks that aren’t public. Could I get in contact with someone to get an OAuth setup?

**Comment by zzorba** [comment]
So the api is still a bit rough (it hasn't been fully converted/tested from the previous ArkhamDB days), that said it's something we're going to be working on in the next couple of weeks so we should be able to get you access soon.  I think the thing we need to proceed is the name of the app and your redirect URL (for the OAuth2 exchange).

If you want to reach out to zzorba#2979 on Discord with that info, we can get you the access once we've dusted off the cobwebs from that section of the codebase.
