### ISSUE TITLE
Search for Nebula decks not working

### ISSUE THREAD

**Issue by ElSapo1969** [zzorba/marvelsdb#121]
In  Decklists/Search/Card Used, Nebula cards are all duplicated and searching for her decks does not work. It returns always no result.
![Screenshot_20210923-005814](https://user-images.githubusercontent.com/91227952/134432955-907a167c-38ec-4478-8a59-8ba247aaa1d5.jpg)

**Comment by Kamalisk** [comment]
I think it is confused by the villain versions, hence why there are so many of her.

**Comment by ElSapo1969** [comment]
Nebula's Ship is surely a single card. Anyway the main problem is that it's not possible to search for a Nebula's deck using one of the Nebulas specific card.

**Comment by Kamalisk** [comment]
added more details to the search list to make it easier to pick the correct cards.
