### ISSUE TITLE
[Feature Request] Browse decklists by hero

### ISSUE THREAD

**Issue by BeetrootShoulders** [zzorba/marvelsdb#127]
Seems like a very natural way of looking for decks is missing - simply being able to browse all the decklists for any given hero. At present the only solution is to search for a deck that includes the hero card, which is cumbersome to say the least.

**Comment by bicycleghost** [comment]
I agree. It's kinda hard to search for a certain hero rn

**Comment by Kamalisk** [comment]
I'll see what I can do to make it easier.
