### ISSUE TITLE
Data Issues - War Machine Pack

### ISSUE THREAD

**Issue by nateyj** [zzorba/marvelsdb#129]
### Identity
War Machine: hero (23001a)
- traits: current = 'S.H.I.E.L.D. Soldier.'; new = 'Avenger. Soldier.'

James Rhodes: alter-ego (23001b)
- traits: current = 'Outlaw.'; new = 'S.H.I.E.L.D. Soldier'
- text: current = '<i>Cybernetic Upgrades</i> - <b>Response</b>: After you play a [[technique]] upgrade, draw 2 cards. (Limit once per round.)' (i.e., Nebula's alter-ego text); new = '<b>Action</b>: Choose a War Machine card in your discard pile and shuffle it into your deck.
<b>Forced Response</b>: After you change to this form, discard each ammo counter from your identity.'

### Allies
Captain Marvel: ally (23013)
- cost: current = 3; new = 5
- subname: current = null; new = 'Carol Danvers'
- attack: current = 2; new = 3

Black Panther: ally (23012)
- subname: current = null; new = 'T''Challa' (escaped single quote: actual value "T'Challa"

Iron Man: ally (23002)
- subname: current = null; new = 'Tony Stark'

### Events
Make the Call: event (23020)
- quantity: current = 1; new = 2

Two Against the World: event (23024)
- traits: current = '.'; new = null

### Upgrades
Upgraded Chassis: upgrade (23004)
- cost: current = 1; new = 3

Gauntlet Gun: upgrade (23005)
- cost: current = 1; new = 2

### Supports
Vigilante Training: support (23033)
- quantity: current = 3; new = 2

**Comment by Kamalisk** [comment]
thanks. should be all fixed now.
