### ISSUE TITLE
Searching for allies of heroes is difficult

### ISSUE THREAD

**Issue by braigo64** [zzorba/marvelsdb#130]
Attempting to search for decks that contain the Iron Man leadership ally card. There are currently 3 Iron Man  cards in the game. The drop down of cards when searching lists 3 Iron Man entries, but it's impossible to tell which cards they refer to. Some additional information in the dropdown to distinguish similarly named cards would be helpful.   However, selecting any of the Iron Man options then adds Tony Stark as a card to the search parameters and returned results are primarily decks using the hero identity Iron Man.

There does not seem to be a way to simply specify the Leadership Ally card Iron Man and return decks that contain that card.  This occurs for any hero that also has an Ally card in the game.

**Comment by Kamalisk** [comment]
![image](https://user-images.githubusercontent.com/3259744/146618875-4800ede7-94fd-45c6-a6ca-87b5fdfb5e7e.png)

Now shows the card type and the card set and number, also shows the aspect color.
And now actually lets you pick cards with the same name as hero cards.
