### ISSUE TITLE
Black Panther missing OKTGN id

### ISSUE THREAD

**Issue by Azmodael** [zzorba/marvelsdb#131]
Black Panther[23012] card exists in OCTGN database, but trying to export a deck containing him does't load any id. I don't know where to see it in OCTGN.

**Comment by Azmodael** [comment]
Update: Got the ID from OTGN files -> <card name="Black Panther" id="b39ca70e-b5c3-44b7-aa2c-e825f506561c">

Should be simple matter to update.

**Comment by Kamalisk** [comment]
black panther seems to have the octgn id, is this still not working?

**Comment by Azmodael** [comment]
I talked to the OCTN MC developer and he added a pull request. If you approved that its probably fixed already?

I just downloaded a deck and its now working.
