### ISSUE TITLE
Giant Wasp dont have correct text and foto

### ISSUE THREAD

**Issue by Freakmod** [zzorba/marvelsdb#132]
In Giant Wasp no have the Text of the card and dont have the correct image https://marvelcdb.com/card/13001c

Please change the card for this https://images-cdn.fantasyflightgames.com/filer_public/26/6a/266a3d69-d375-4dbe-8317-90466658ec7f/mc13en_wasp-giant.png

**Comment by Kamalisk** [comment]
thanks. fixed.

**Comment by Freakmod** [comment]
the text in the left no apear 
![imagen](https://user-images.githubusercontent.com/95939624/146685106-9a48d4c5-f9fd-4354-b61a-22102f605f4b.png)

the text with the stars on the card 
![imagen](https://user-images.githubusercontent.com/95939624/146685124-2c257f3b-4da9-46f3-8667-09b13c5c05fc.png)
