### ISSUE TITLE
Data issue - No energy resource in Ready to Rumble

### ISSUE THREAD

**Issue by Freakmod** [zzorba/marvelsdb#133]
The card Ready to Rumble https://marvelcdb.com/card/21022 dont have the energy resource in the database when you create a deck
![imagen](https://user-images.githubusercontent.com/95939624/145733610-30b239b0-75af-4210-b119-7b2bc63b4956.png)

This is a image of the card 
![imagen](https://user-images.githubusercontent.com/95939624/145733761-6a74d2e2-72ab-4c7d-9929-d095971283b4.png)

**Comment by Kamalisk** [comment]
thanks for the report. fixed now.
