### ISSUE TITLE
All cards of Valkyrie  pack no have text of the cards

### ISSUE THREAD

**Issue by Freakmod** [zzorba/marvelsdb#137]
All the specific cards of Valkyrie dont have text. and the new cards on the database (smash the problem (https://marvelcdb.com/card/25019), quick strike (https://marvelcdb.com/card/25018), the best defense... (https://marvelcdb.com/card/25020), the biforst (https://marvelcdb.com/card/25023), etc)

I know the image of the card is difficult but the text of the card is important to create a deck.

To check the text of the cards use https://hallofheroeslcg.com/brunnhilde-valkyrie/

And official cards is in the notice of the pack https://www.fantasyflightgames.com/en/news/2021/8/26/halls-of-valhalla/ not all but is something

**Comment by Kamalisk** [comment]
I am aware of the lack of text, someone added all the cards without it, so I added them as they can be used for deck building if you know what the cards do, and will add the text myself (if no one else does) when I get the chance.
