### ISSUE TITLE
Vision Pack Not Showing Up to Add to Decks

### ISSUE THREAD

**Issue by Yusnaan** [zzorba/marvelsdb#139]
Cannot add vision pack cards to decks or # link them in descriptions.

**Comment by Nerman8r** [comment]
I think I'm having a similar problem now with Iceman.  If I look at an Iceman deck, the card list area is blank.  If I try to create an Iceman deck, I get a loading swirly that never goes away, if I mouseover the name of an Iceman card, no description pops up, and I can't add Iceman cards to my decks.  This issue only happens with Chrome, and only with Iceman.  If I switch to Firefox everything seems to work fine.
