### ISSUE TITLE
[Feature request] "Select packs from your collection" function under decklist -> search

### ISSUE THREAD

**Issue by dspice** [zzorba/marvelsdb#141]
The ability to select the packs you own (from your account collection) instead of having to select them manually each time when searching would be amazing. ArkhamDB has that functionality enabled using the same software, see attached screenshot. Ta :)

![image](https://user-images.githubusercontent.com/9410925/154457108-b1e9bb2e-9c77-4c17-a1db-807a243bfc86.png)

**Comment by wicherekp** [comment]
+1
I just logged in to ask for that. So useful with small collections like mine.

**Comment by Kamalisk** [comment]
should work the same as arkhamdb now.

**Comment by dspice** [comment]
Thanks so much!!!!!
