### ISSUE TITLE
Add missing images to MarvelCDB

### ISSUE THREAD

**Issue by TooPick** [zzorba/marvelsdb#143]
Hi,

I saw this repo https://github.com/zzorba/marvelsdb-json-data for all text data and translations but I wanted to know if there is a way to update missing images. If I search in OCTGN image packs and rename the image with MarvelCDB card code, there is a repo or a platform to send the image and update it on the app ?

Thank you in advance :)

**Comment by Kamalisk** [comment]
there is no repo, it is just images stored on the server, but if you wish to rename images and send a zip of the images I can dump them into the right place.

**Comment by TooPick** [comment]
Thank you for your answer !
During my lunch time I've made a small script to convert all image name of OCTGN to card code.
I've tried it with galaxy most wanted pack. I just had to remove one by one all images that are already on mavelcdb (don't know if duplicates can cause touble) but here is a zip of all images https://drive.google.com/file/d/1-kuWKFYjL14mfzDK_ZsU0XkX4O4sMnsO/view?usp=sharing with duplicates removed.
I could make this for all packs, now my script is ready it take be just a second to convert and maybe 10min to check one by one if the image doesn't exist on the website.
Sorry if my english is not really good, my main language is French ^^

**Comment by Kamalisk** [comment]
cool. I can easily make it not replace files that already exist when copying the files over. just getting the images with the correct file name is the important part. Thanks a lot!

**Comment by TooPick** [comment]
Ok, nice, I will try to do that for other packs when I have time and I'll send you all zip files even with duplicates if it's not important ! :)

**Comment by TooPick** [comment]
Just made a zip for the hood pack : https://drive.google.com/file/d/1FNCddgjTYQFO5BNRxDJmqXyolmEpYkoj/view?usp=sharing
I've looked at all other packs on mcdb and I think it's the only one that had missing card images. Let me know if you want the zip for another pack, my script can do it in less a second ^^

**Comment by Kamalisk** [comment]
Added them now. If you do future packs, then just make a new issue. Thanks a lot!
