### ISSUE TITLE
Some Valkyrie encounter cards are replaced with GS ones

### ISSUE THREAD

**Issue by dimitrisnl** [zzorba/marvelsdb#157]
<img width="1384" alt="Screen Shot 2022-08-28 at 1 11 11 PM" src="https://user-images.githubusercontent.com/4951004/187068792-46be282f-2220-4e10-b2f8-55ae3c9ac106.png">

https://marvelcdb.com/set/valk/scan/all/set/2

You can see that instead of the correct Nemesis,  there are some Lizard cards. Taking a look at the JSON data to understand where this might be caused.

**Comment by dimitrisnl** [comment]
Valk nemesis is `25027` with Lizard is `27027` - somewhere something went wrong

**Comment by dimitrisnl** [comment]
The json data seems to be correct. Seems like the uploaded images are the same

- https://marvelcdb.com/bundles/cards/25027.png
- https://marvelcdb.com/bundles/cards/27027.png

**Comment by dimitrisnl** [comment]
Revisiting the code, I think the error lies with FFG, specifically with their images

https://github.com/zzorba/marvelsdb/blob/master/src/AppBundle/Command/ImportImagesCommand.php#L69-L76

The previews code should produce the following URL for the Valkyrie minion

https://lcgcdn.s3.amazonaws.com/mc/MC25en_28.jpg

but it's not working, so I need to further investigate. I believe that they have uploaded wrong images or something

**Comment by dimitrisnl** [comment]
I see that all the links start to break after the Quicksilver pack, which is the last one uploaded in cardgamedb - so maybe something is wrong with my link constructio

<img width="605" alt="Screen Shot 2022-08-28 at 1 56 58 PM" src="https://user-images.githubusercontent.com/4951004/187070601-e4a78430-965a-4e53-b4e4-c704e8e4da6c.png">

**Comment by dimitrisnl** [comment]
@zzorba I noticed that we manually add the cards on the server now, so my conclusion is that cards

- https://marvelcdb.com/bundles/cards/25027.png
- https://marvelcdb.com/bundles/cards/25028.png
- https://marvelcdb.com/bundles/cards/25029.png

are uploaded wrong.

**Comment by Kamalisk** [comment]
yeah, ffg have long since stopped providing sensible images. THe images were provided to me I believe. so I guess there were just mistakes there.

**Comment by dimitrisnl** [comment]
@Kamalisk Can we use the ones from the hall of heroes? 

They are of great quality https://hallofheroeslcg.com/sinister-motives/
