### ISSUE TITLE
Poor performance

### ISSUE THREAD

**Issue by remulak3** [zzorba/marvelsdb#159]
Hey, looks like the website that is running on this repo has really poor performance. I don't know if this was present earlier, but for me it made it barely usable. Could anyone familiar with this code look at it?

**Comment by Kamalisk** [comment]
It should hopefully be better now?

**Comment by remulak3** [comment]
Yes, now its much better. Thanks ^^ Could you tell me what was the cause of this problem?

**Comment by Kamalisk** [comment]
It was an issue with the database. I have hopefully solved it to that the heavy load doesn't cause it again. We will see.
