### ISSUE TITLE
Unable to search for decks

### ISSUE THREAD

**Issue by phatram32** [zzorba/marvelsdb#16]
When I select Captain America’s shield it yields zero results even though there are decks posted for this hero. I also tried to select by class and same thing happens 
![7FC665E9-95B7-4999-90FE-0066A0E40906](https://user-images.githubusercontent.com/35791204/71648028-f72b9300-2ccc-11ea-9413-75e33b0e6c16.png)

**Comment by Kamalisk** [comment]
it should work now.

**Comment by phatram32** [comment]
It is working like a charm! Many thanks!
