### ISSUE TITLE
My Deck - Can't Save with more than 50 cards

### ISSUE THREAD

**Issue by bradcadams** [zzorba/marvelsdb#163]
When I attempt to save a deck with greater than 50 cards I receive an error message that the deck has too many cards and then all of the cards are removed from deck. It would be nice to be able to save work in progress decks that don't meet the valid requirements. Also, it shouldn't remove the work in progress.

**Comment by Kamalisk** [comment]
It should still save with more than 50 cards. It works for me. 

![image](https://user-images.githubusercontent.com/3259744/203442537-83b2ab71-fde3-4c21-b054-776b51c82313.png)
