### ISSUE TITLE
Search engine is not working correctly

### ISSUE THREAD

**Issue by szwalkowski** [zzorba/marvelsdb#164]
1. Go to https://marvelcdb.com/search
2. pick 'Main Scheme' in 'Type'
3. Search (find?q=t%3Amain_scheme&decks=player)
EXPECTED: get all main schemes cards
CURRENTLY: invalid filter is generated, no card selected? Look at URL - decks=player for some reason

1. Go to https://marvelcdb.com/search
2. pick only 'aggression', disable other classes
3. Search
EXPECTED: get all aggression cards
CURRENTLY: no filter is generated

1. Go to https://marvelcdb.com/search
2. pick only 'encounter', disable other classes
3. Search
EXPECTED: get all encounter cards
CURRENTLY: no filter is generated

Generaly I guess for all other same

**Comment by Kamalisk** [comment]
![image](https://user-images.githubusercontent.com/3259744/203442986-fb00432b-8876-4137-aa5d-4ceb19291f4e.png)

by default it only searches player cards, so schemes wont turn up. 

Searching for agression works fine for me.
