### ISSUE TITLE
Images for Wolverine / Storm / MojoMania

### ISSUE THREAD

**Issue by TooPick** [zzorba/marvelsdb#165]
@Kamalisk 
Hey, me again !

I've packed all images for Wolverine, Storm and MojoMania : https://drive.google.com/file/d/1tOOCiaYuyREZ6EebVs_LmCX-VqF_OEj3/view?usp=sharing

I also noticed that images for Ronan Modular Set are missing, here they are : https://drive.google.com/file/d/1m6z__vjx0tV2T_fYBxW2AL-EV5-ryQ3J/view?usp=sharing

**Comment by Kamalisk** [comment]
thanks. Very much apperciate this even if I took too long to do it.
