### ISSUE TITLE
I Can't Register

### ISSUE THREAD

**Issue by SaintMatt1234** [zzorba/marvelsdb#166]
Greetings,
I tried to register for MarvelCDB. The URL I received in my activation email is a dead URL that does nothing. For what it is worth, I also sent a message to kamalisk on reddit and have not yet heard back (kamalisk may have been traveling for the holidays). Could it be because my username contained a punctuation mark? Can I have my email "reset" to pick a different username? Any guidance is appreciated.
Matt

**Comment by Kamalisk** [comment]
symbols and spaces are not allowed, though it does not do a good job of telling you.
