### ISSUE TITLE
Enhanced Reflexes  is also in the Gamora Hero Pack #32 card with three copies

### ISSUE THREAD

**Issue by Stevesiajke** [zzorba/marvelsdb#172]
Enhanced Reflexes  is also in the Gamora Hero Pack #32 card with three copies
Please Please, check it!

**Comment by Stevesiajke** [comment]
@zzorba @cmaher @alberto-bottarini @Kamalisk

**Comment by Kamalisk** [comment]
it is odd since the card is not in the actual gamora deck list, just a random duplicate in the pack.
