### ISSUE TITLE
Update README/Help getting set up

### ISSUE THREAD

**Issue by jordanweiler** [zzorba/marvelsdb#173]
I'm trying to set up this repo locally to better test the JSON changes from https://github.com/zzorba/marvelsdb-json-data and I'm stuck on the last step in the README which says run `php bin/console server:run`. I get an error message of `There are no commands defined in the "server" namespace.`.

I'm hoping this is just a silly user error that can be marked up to my lack of knowledge of PHP/Symfony. If that's not the correct command to start up the server, could the README get updated to reflect the new command? If that is the correct command, are there any steps missing from the set up guide to get this up and running?

I'm running:
* PHP 7.3
* MySQL 8.0 (I updated the config.yml file from 5.6 and was able to fully populate the tables)

**Comment by Kamalisk** [comment]
The symfony version is very old and am still trying to upgrade it, I have never used the server command myself, so I have no idea if it works or not.

**Comment by jordanweiler** [comment]
I tracked down a similar issue with the arkhamdb repo which this was cloned from (https://github.com/Kamalisk/arkhamdb/issues/431) and finally figured out how to run it. I'll try to create a PR for that soon.

**Comment by gaetan-petit** [comment]
> The symfony version is very old and am still trying to upgrade it, I have never used the server command myself, so I have no idea if it works or not.

Do you need help with Symfony upgrade?

**Comment by gaetan-petit** [comment]
@Kamalisk I still could sparz a few hours here and there to help you with upgrading things. Do you need help?
