### ISSUE TITLE
Resource count

### ISSUE THREAD

**Issue by itskando** [zzorba/marvelsdb#18]
**Additional Resource Categories**:

The current resource graph states how many resources are in a deck. I feel that a more telling graph would list quantities of what is printed on each card, such as, with Captain Marvel:

```
P   : 10
S   : 10
E   : 20
W   : 01 (Leadership: The Power of Leadership)

PP  : 01 (Basic: Strength)
SS  : 01 (Basic: Genius)
EE  : 01 (Basic: Energy)

EEE : 02 (Captain Marvel: Energy Absorption)
```
This helps people better understand the chances of drawing what is printed for a much more robust set of scenarios.

**Include Hero Faction Count in Other Charts**:

It would be helpful to show the number of Hero cards in each of the Resource Counts at the bottom of each bar in a different color, representing that this portion of the count is not removable.

It would be similarly helpful to show the number of hero cards in the Card Cost chart by adding a separate line, again since the Hero cards of these costs are not removable.

**Comment by itskando** [comment]
Added further clarifications.

**Comment by s3rek** [comment]
#30 Maybe this will help.

**Comment by Kamalisk** [comment]
Hopefully this is fixed now thanks to the graph update by @s3rek
