### ISSUE TITLE
[FEEDBACK] Storm Doesn't Show Consequential Damage Correctly : MarvelCDB

### ISSUE THREAD

**Issue by yeokaiwei** [zzorba/marvelsdb#187]
Hi,
![storm](https://github.com/zzorba/marvelsdb/assets/36597018/1dbdcb0a-dedb-4300-a56f-3de91d195d25)

If you look at the Storm Ally card page, you will notice that consequential damage doesn't appear correctly on the card.

Could the correct consequential damage be added?

Thank you.

**Comment by fredmilhau** [comment]
![image](https://github.com/zzorba/marvelsdb/assets/35406186/c436958b-03f3-41ab-97b7-609f33a85588)

https://marvelcdb.com/card/34021

Now consequential value is ok, we should be able to close this issue now.
