### ISSUE TITLE
Only allowed to add one Team Investigation to a deck

### ISSUE THREAD

**Issue by DapperOrangutan** [zzorba/marvelsdb#206]
There are 3 Team Investigation's in Domino's deck in NeXt Evolution. Currently, you can only add 1 in the Deckbuilder.
![IMG_0233](https://github.com/zzorba/marvelsdb/assets/39973093/f2fa51d0-0b9d-4e35-83ab-c572479b2e8c)

**Comment by jordanweiler** [comment]
This should have already been fixed with https://github.com/zzorba/marvelsdb-json-data/pull/412

**Comment by DapperOrangutan** [comment]
As of five minutes ago, it's still only allowing me to pick one Team Investigation.
![Team Investigation](https://github.com/zzorba/marvelsdb/assets/39973093/2ed64eca-7937-492f-aa74-65b16accef71)

**Comment by DapperOrangutan** [comment]
Ok, thanks for checking.

**Comment by jordanweiler** [comment]
We should be able to close this issue now. I'm seeing 3 available Team Investigation cards when building a Justice deck on marvelcdb.
