### ISSUE TITLE
Api does not seem to expose encounter cards

### ISSUE THREAD

**Issue by bkkoluch** [zzorba/marvelsdb#219]
I can query encounter cards by `/api/public/card/{card_code}` endpoint, but those are not returned in `/api/public/cards/`.
Maybe some filter could be available in `/api/public/cards/` endpoint to query by type? 
For example `{'faction' : 'encounter'}` would return all encounter cards.

**Comment by Kamalisk** [comment]
its not well documened, but I believe ?encounter=1 will also fetch the encounter cards.

**Comment by bkkoluch** [comment]
@Kamalisk oh my, thank you, I've had totally no idea 👍.

**Comment by bkkoluch** [comment]
@Kamalisk is there a possibility to filter out hero cards and only fetch counter ones?

For example `?encounter=1&hero=0` or sth of that sort?
