### ISSUE TITLE
Packs filter doesn't fetch decks with cards belonging to multiple packs

### ISSUE THREAD

**Issue by AlexKibo88** [zzorba/marvelsdb#227]
Hi,

When I search for a deck with my collection filter applied, sometimes some decks are not displayed only because certain cards belongs to a pack which is different than the one that I own, although the card is just a reprint.

For instance:

![image](https://github.com/zzorba/marvelsdb/assets/8451972/2024fab8-9925-45ff-836d-0c6fee52c14e)

Here, since I don't onw the Hulk package, and this user added "Toe to Toe" to his deck, the card is shown as not available, thus the entire deck is not fetched at all. However, I happen to own the Mutant Genesis box, and "Toe to Toe" exists there too, so I should get that deck as well.

I guess, since card names are unique, the filter should be revised not only comparing maybe the ID and the original package a card belongs to, but even its name ("Toe to Toe" from Hulk, "Toe to Toe" from Mutant Genesis).

Thanks!

**Comment by AlexKibo88** [comment]
Any updates on this issue? I wanna stress out, this bug is quite annoying, and prevents users from fetching many available decks...

**Comment by Kamalisk** [comment]
It might be a bit slower, but I think I have managed to fix it, so when filtering decklists by collection it includes all duplicates of cards. I tested with the above example and found it to work, it hopefully covers all situtations.
