### ISSUE TITLE
Side Scheme not appearing in deck creation

### ISSUE THREAD

**Issue by gmartinez1985** [zzorba/marvelsdb#236]
When creating a new deck, the side schemes doesn't appear.
![image](https://github.com/zzorba/marvelsdb/assets/55528370/c04a9779-623b-4801-8259-9b37259cc34a)

**Comment by Kamalisk** [comment]
it works for me. Do you have side schemes in your collection?

**Comment by gmartinez1985** [comment]
> it works for me. Do you have side schemes in your collection?

Many thanks @Kamalisk. That was the issue. I have updated my collection with products containing side schemes, and now I can see them.
