### ISSUE TITLE
Iceman not working with Chrome

### ISSUE THREAD

**Issue by Nerman8r** [zzorba/marvelsdb#237]
Hey, thanks for making such a useful website!

I'm having a problem with Iceman. If I look at an Iceman deck, the card list area is blank. If I try to create an Iceman deck, I get a loading swirly that never goes away, if I mouseover the name of an Iceman card, no description pops up, and I can't add Iceman cards to my decks. This issue only happens with Chrome, and only with Iceman. If I switch to Firefox everything seems to work fine.  Chrome also works fine when in incognito mode.

**Comment by Kamalisk** [comment]
its probably a caching issue in chrome then. Best I can say is to clear the cache or try to reload the page a lot.
