### ISSUE TITLE
consequential icon not displayed

### ISSUE THREAD

**Issue by mmougy** [zzorba/marvelsdb#252]
It seems the [consequential] symbol is not supported

[Coordinated Attack](https://marvelcdb.com/card/33016)
![image](https://github.com/user-attachments/assets/07b3c487-5bfa-4dac-8e78-18a139e9927f)

[Uncanny X-Force](https://marvelcdb.com/card/40022)
![image](https://github.com/user-attachments/assets/6d22d22e-5959-4f08-bd2f-4b0ebd0f9da5)

[Gentle](https://marvelcdb.com/card/36016)
![image](https://github.com/user-attachments/assets/8be49023-ad14-4816-b742-c4a9598ce90b)

**Comment by jordanweiler** [comment]
This feature has been fixed on https://github.com/zzorba/marvelsdb/pull/204. We'll need to update the JSON text to use `[cost]` instead of `[consequential]`.
