### ISSUE TITLE
OCTGN Export not working

### ISSUE THREAD

**Issue by q3c0** [zzorba/marvelsdb#33]
Hello, and thanks in advance for the work you have been doing.

I was wondering if the export functionality for OCTGN is working correctly: when exporting the following, I see that only Events are in the .o8d file: https://marvelcdb.com/decklist/view/21/energy-iron-man-1.0#

```<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<deck game="a6d114c7-2e2a-4896-ad8c-0330605c90bf" sleeveid="0">
  <section name="Investigator" shared="False">
    <card qty="1" id="9780ba79-44e4-4530-b865-5983a60372b0">Iron Man</card>
    <card qty="1" id="">Iron Man</card>
  </section>
  <section name="Asset" shared="False">
  </section>
  <section name="Event" shared="False">
    <card qty="3" id="08234002-9dd8-4a63-b012-7a9647b49b8a">Repulsor Blast</card>
    <card qty="2" id="98a1d5d7-e576-4da3-8d13-82fbb2042bfc">Supersonic Punch</card>
    <card qty="3" id="8c071923-f2b1-44e9-a579-db84bb823cc0">For Justice!</card>
    <card qty="1" id="cef2d14c-8e58-48e3-9330-5342b583f532">Emergency</card>
    <card qty="3" id="270f6e5d-6331-4211-a3a1-d0bdcc9fa4e2">Haymaker</card>
  </section>
  <section name="Skill" shared="False">
  </section>
  <section name="Weakness" shared="False">
  </section>
<notes><![CDATA[]]></notes>
</deck>
```

I took this one as an example, but I also tried other decks and again only events are downloaded.

Am I missing something?

**Comment by zzorba** [comment]
Hi @q3c0 
Looks like its still exporting in the Arkham format.  I'll talk to the OCTGN maintainer and see about getting that updated.

**Comment by q3c0** [comment]
Thank you very much! I suspected that when I saw "Investigator" and the fact that only Events, which are the only "shared category" I'd say, are exported.

**Comment by Kamalisk** [comment]
I have updated the ocgtn exports. No idea if they work. 
If they don't, and you have an example of what ocgtn decks look like let me know.
