### ISSUE TITLE
Corrupted Octgn files

### ISSUE THREAD

**Issue by EmergencyMe** [zzorba/marvelsdb#41]
Hi All, 

When I try to load up a deck file to Octgn, I get an error that say the .o8d file is corrupt.  Freshly exported from the deckbuilder.  I am not savvy enough with Octgn to be much use as a trouble shooter.  :(

J

**Comment by Kamalisk** [comment]
I have updated the ocgtn exports. No idea if they work. 
If they don't, and you have an example of what ocgtn decks look like let me know.
