### ISSUE TITLE
Suggestion: Is It possible to get data from API in spanish? 

### ISSUE THREAD

**Issue by ikeinyyo** [zzorba/marvelsdb#44]
I know the web can show data in spanish, but i don't know if is possible to get cards data from API.

https://github.com/zzorba/marvelsdb/blob/8ffd227374d41ab31770bb5bd52a8ee3d649259f/src/AppBundle/Controller/ApiController.php#L146

**Comment by zzorba** [comment]
You can, just prefix the URL with the card name, and I believe it works.

`https://es.marvelcdb.com/api/public/cards/`

**Comment by ikeinyyo** [comment]
Perfect! Thank you! :D
