### ISSUE TITLE
Feature Request: Advanced Search - Keyword/Attribute

### ISSUE THREAD

**Issue by DoxaLogosGit** [zzorba/marvelsdb#45]
I was trying search for cards that had the "spy" attribute/keyword, but I didn't see an option. I think this would be a very nice feature to have.  The ability to do an advanced search based on a keyword or card attribute would be critical to helping build decks more easily.  If you add the option to search only the decks you own would be the cherry on top!

**Comment by Kamalisk** [comment]
Those are called "traits". Which is searchable by "k:spy" for example.
