### ISSUE TITLE
Add modular key?

### ISSUE THREAD

**Issue by Ian-n2** [zzorba/marvelsdb#47]
Hey there I am currently building an app that will randomly pick a villain and side scheme (modular) to play against. However there doesn't seem to be anything to set the modular side schemes apart from the others ie the hero ones. As it currently stands the app my tell the player to fight against ultron with "Generation why?" (Ms. Marvel's nemesis scheme) as the side scheme. Is there a way you could a modular key to the schemes with a value or true or false? or any other way?

**Comment by Kamalisk** [comment]
I added a card_set_type_code to the card data. 
"modular" for the modular sets, otherwise, "nemesis", "hero", "villain", "expert", and "standard" for the other types.
