### ISSUE TITLE
Magical Enhancements misnamed

### ISSUE THREAD

**Issue by funkymonkeymonk** [zzorba/marvelsdb#48]
Not sure where the data is stored or I'd send the PR myself but I noticed the card "Magical Enhancements" is misnamed as "Magic Enhancements." I'm happy to learn how to fish on this one and send the PR myself or just read the changeset if you link it here so that next time I can send a fix instead of just notifying you.

**Comment by Kamalisk** [comment]
https://github.com/zzorba/marvelsdb-json-data
