### ISSUE TITLE
Cannot search for S.H.I.E.L.D. trait

### ISSUE THREAD

**Issue by jmrburgard** [zzorba/marvelsdb#51]
The S.H.I.E.L.D. trait is not searchable, either through the drop down in the main card list or by k:S.H.I.E.L.D. in the card search. 

(Side note: the help at the bottom of the search list has an example from AH which was rather confusing to me before I figured it out).

**Comment by MakeYourPieceGames** [comment]
Workaround: Search for k:"S.H.E.I.L.D" (omit the last period). This seems to be because the templating ends every trait with a period, but the SHIELD trait normally ends with one and they didn't double it up.

**Comment by Kamalisk** [comment]
I fixed traits so it can have . in them, so can search for the shield trait with dots now (but not with a trailing . )
Also updated the example, and S.H.I.E.L.D is selectable from the search page also.
