### ISSUE TITLE
Resource filters don't work

### ISSUE THREAD

**Issue by canyouflybobbi** [zzorba/marvelsdb#52]
In the deckbuilding screen when I try to filter by any of the resource filters
rp – Physical
rm – Mental
re – Energy
rw – Wild
nothing happens, for example
rw:1
rp>0
other filters work, for example
o:1
h>0
If I try the same in the cardlist section it works correctly.
Thanks
[edit - to specify that this issue is in the deck building section]

**Comment by Kamalisk** [comment]
wasn't allowing the filters with two or more letters. Should work for them all now.
