### ISSUE TITLE
Email registration does not send an email

### ISSUE THREAD

**Issue by strgzrwag** [zzorba/marvelsdb#53]
Tried multiple times to register, never got a reply. Yup, checked SAM, filters etc. No joy.
Site looks great & I would love to contribute! So please look into this. 

Thank you,

strgzrwag

**Comment by Kamalisk** [comment]
your email server seemed to be rejecting my mails. Regardless, I have enabled your account.

**Comment by strgzrwag** [comment]
Thanks! I thought it might be that. Yahoo bought and hosts sbcglobal.net and it has been a pain in the assto deal with because of issues like this. I appreciate your prompt attention and look forward to participatingin testing the existing decks and maybe even posting a few of my own!
Again, many thanks!
Rick (strgzrwag)

    On Saturday, August 8, 2020, 5:16:35 PM CDT, Allan Clements <notifications@github.com> wrote:  
 
 


your email server seemed to be rejecting my mails. Regardless, I have enabled your account.
