### ISSUE TITLE
card_set_type_name_code wrong on some schemes

### ISSUE THREAD

**Issue by Ian-n2** [zzorba/marvelsdb#60]
Hey again,
 I am looking at the green goblins Schemes and I was wondering if the following should be set to "villain" instead of "modular" as the are part of the green goblin/Norman Osborn 's set of cards and not their own set. 

Goblin Reinforcements 
Goblin Nation
Overrun
Collapsing Bridge
Oscorp Manufacturing 
Payoff

Here is Rhino's side scheme Crowd Control with Norman Osborn's (Risky Business) side scheme Payoff both belong to a villain but one has card_set_type_name_code: "modular". 
This is bringing all the side schemes from the "gob" pack when I sort the api.

**Comment by Kamalisk** [comment]
The goblin villain sets were set incorrectly. fixed now.
