### ISSUE TITLE
Hawkeye Card Updates

### ISSUE THREAD

**Issue by sidersdd** [zzorba/marvelsdb#70]
Traits on Hawkeye's Electric Arrow should be "Arrow. Attack." not "Arrow. Thwart."
https://marvelcdb.com/card/04007

**Comment by sidersdd** [comment]
Traits on Expert Marksman should be "Skill."
https://marvelcdb.com/card/04010

**Comment by sidersdd** [comment]
Expert Marksman Type should be "Upgrade" instead of "Support" as well

**Comment by wargfn** [comment]
Changes entered into the Data Repository.

**Comment by jordanweiler** [comment]
Fix has been made. This issue can be closed.
