### ISSUE TITLE
Data Issue - Abomination

### ISSUE THREAD

**Issue by MakeYourPieceGames** [zzorba/marvelsdb#71]
https://marvelcdb.com/find?q=abomination 

Traits on card: Gamma. Elite. 
Traits in db: Hydra. Elite.

Flavor text: pitful (Should be pitiful, with the second I)

**Comment by wargfn** [comment]
Change Made into Data Repository.

**Comment by jordanweiler** [comment]
Fix has been made. This issue can be closed.
