### ISSUE TITLE
Rhino III text has wrong “When Revealed” effect

### ISSUE THREAD

**Issue by gamedogmillionrie** [zzorba/marvelsdb#74]
Stage III Rhino “When Revealed” effect should be “Stun all heroes”.

**Comment by wargfn** [comment]
@gamedogmillionrie Heads up, you might want to go back to your card and look at it. If you got one that says "Stun all heroes" that looks like a misprinted card, could be worth a LOT.

**Comment by jordanweiler** [comment]
The image for Rhino III (https://marvelcdb.com/card/01096) on MarvelCDB and Hall of Heroes both show the text as "**When Revealed**: Stun each hero."

The card in MarvelCDB shows that text as well so we should be able to close this issue as it seems to be correct.
