### ISSUE TITLE
Sentry has his subtitle misspelled

### ISSUE THREAD

**Issue by Nintennerd** [zzorba/marvelsdb#76]
It is currently spelt "Rober**y** Reynolds"

The correct spelling is "Rober**t** Reynolds"

**Comment by rdonnelly** [comment]
Thanks, will be fixed via https://github.com/zzorba/marvelsdb-json-data/pull/70/commits/053d81cb263c895eb9e47cf3ea79cb834b2c91eb in https://github.com/zzorba/marvelsdb-json-data/pull/70!
