### ISSUE TITLE
Ant-Man Cards Missing from Other Characters

### ISSUE THREAD

**Issue by i2xCross** [zzorba/marvelsdb#78]
When building an Ant-Man deck, all cards from his character pack are available (Ronin, Moxie, Moment of Triumph, Muster Courage, Team Building Exercise, etc).

But when building a deck with other characters, none of the cards from the Ant-Man pack are visible or usable when building.

**Comment by wargfn** [comment]
Have you added the Ant-man pack to your collection, because this works fine under my account.

**Comment by i2xCross** [comment]
Well now I just feel silly. 

I really thought I had. But sure enough, that's what the problem was. Thanks!
