### ISSUE TITLE
Data Issue - Kang set "Weakened" incorrect card number

### ISSUE THREAD

**Issue by sm3ss** [zzorba/marvelsdb#79]
https://marvelcdb.com/card/11018

The card "Weakened" is listed as card 22-24 within Kang, but it should be 22-23

![image](https://user-images.githubusercontent.com/73089982/99729005-4830ab00-2a88-11eb-83ea-f1c3f8c58a58.png)

**Comment by wargfn** [comment]
Correct the number of weakened cards on the Data Repository.
