### ISSUE TITLE
Italian Version

### ISSUE THREAD

**Issue by FeyrBert** [zzorba/marvelsdb#8]
Hey guys!
Whenever you're ready to implement other languages let me know, I'll work on the Italian version of the site like what we're doing with the Arkham Horror LCG :)

Cheers!
Bertrand

**Comment by zzorba** [comment]
Thanks FeyrBert, I hope to do some work on the site over the holiday break and will see what can be done to get the translations extracted then.

**Comment by alberto-bottarini** [comment]
Any news? I manage a telegram community and some of us can help

**Comment by Kamalisk** [comment]
@alberto-bottarini 

Added placeholder translations to be translated.

https://github.com/zzorba/marvelsdb-json-data/tree/master/translations/it

So translate these, and when some are done I can add italian to the language options.

**Comment by alberto-bottarini** [comment]
Great, i will pr in a short

**Comment by alberto-bottarini** [comment]
We are working on it, you can close
