### ISSUE TITLE
"Nerves of Steel" text missing a word

### ISSUE THREAD

**Issue by WastelandSniper1776** [zzorba/marvelsdb#82]
The text for Nerves of Steel reads:

**Resource:** Exhaust Nerves of Steel → generate a [energy] resource for a event.

It should read:
**Resource:** Exhaust Nerves of Steel → generate a [energy] resource for a **defense** event.

**Comment by lostie** [comment]
@WastelandSniper1776 Thanks for reporting the wording issue. Card data though is updated in another [repo](https://github.com/zzorba/marvelsdb-json-data/). I'll try and add these changes to that repo.

**Comment by wargfn** [comment]
It isn't actually missing. <b?Deffense</b> hides the word instead of
showing it. Just examine the source for the card.
