### ISSUE TITLE
Api get villains

### ISSUE THREAD

**Issue by sergiqm94** [zzorba/marvelsdb#9]
Hello,

I'm creating a small web testing application to randomly choose which heroes and villains to play Marvel Champions LCG.

Why in the API request https://marvelcdb.com/api/public/cards/ the villains cards aren't included?
Can you show them or create an other endpoint for this cards?

Thank you.

**Comment by zzorba** [comment]
I believe you need to add `?encounter=1` to the end of the request to get the non player cards.

Sounds like a cool project, let us know if you need anything else
