### ISSUE TITLE
The image shown for Giant Wasp is Tiny Wasp

### ISSUE THREAD

**Issue by michaelgwelch** [zzorba/marvelsdb#91]
Navigate to [giant wasp](https://marvelcdb.com/card/13001c)

And you'll see an image of tiny wasp

<img width="758" alt="image" src="https://user-images.githubusercontent.com/826112/111040366-510f0900-83f8-11eb-8d71-c15ee5ec6598.png">

**Comment by michaelgwelch** [comment]
The url for the image looks correct: https://marvelcdb.com/bundles/cards/13001c.jpg ; it would appear that the tiny card is used twice with two names `13001b.jpg` and `13001c.jpg`. I don't know where the images are stored otherwise I'd just attempt a pull request.

**Comment by Kamalisk** [comment]
now has giant wasp.
