### ISSUE TITLE
Data Issues

### ISSUE THREAD

**Issue by nateyj** [zzorba/marvelsdb#93]
**Column issue(s): traits**

Card code: 11030 (Ancient Warrior)
DB: Solider. Temporal.
Fix: Soldier. Temporal.

**Column issue(s): type_code, type_name**

Card code: 04099 (White Tiger)
DB: upgrade, Upgrade
Fix: ally, Ally

Card code: 04055 (The Viper's Ambition)
DB: resource, Resource
Fix: side_scheme, Side Scheme

**Column issue(s): threat**

Card code: 01138 (Assault on NORAD)
DB: 3
Fix: 10

Card code: 01139 (Countdown to Oblivion)
DB: 3
Fix: 5

Card Code: 11008 (The Master of Time)
DB: 0
Fix: null

**Column issue(s): base_threat**

Card Code: 11008 (The Master of Time)
DB: 0
Fix: null

**Comment by Kamalisk** [comment]
fixed.
